# Generated by Django 2.0.3 on 2018-03-29 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUserId', models.CharField(max_length=60)),
                ('toUserId', models.CharField(max_length=60)),
                ('status', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('Text', models.CharField(max_length=1000)),
                ('isDelete', models.BooleanField(default=False)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
