#FROM amancevice/pandas:0.21.0-python3-alpine
FROM python:3.5-slim

WORKDIR /app/src
ADD requirement.txt /app/requirement.txt
RUN apt-get update && apt-get install -y gcc && pip install --upgrade pip && pip install -r /app/requirement.txt
