# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: aws_email.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import aws_email_pb2


class EmailServiceBase(abc.ABC):

    @abc.abstractmethod
    async def SendMail(self, stream):
        pass

    def __mapping__(self):
        return {
            '/protos.EmailService/SendMail': grpclib.const.Handler(
                self.SendMail,
                grpclib.const.Cardinality.UNARY_UNARY,
                aws_email_pb2.EmailRequest,
                aws_email_pb2.EmailResponse,
            ),
        }


class EmailServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.SendMail = grpclib.client.UnaryUnaryMethod(
            channel,
            '/protos.EmailService/SendMail',
            aws_email_pb2.EmailRequest,
            aws_email_pb2.EmailResponse,
        )
