# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aws_email.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='aws_email.proto',
  package='protos',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x61ws_email.proto\x12\x06protos\"z\n\x0c\x45mailRequest\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\n\n\x02\x63\x63\x18\x03 \x03(\t\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12\x0f\n\x07\x63harset\x18\x05 \x01(\t\x12\x10\n\x08textBody\x18\x06 \x01(\t\x12\x10\n\x08htmlBody\x18\x07 \x01(\t\"\"\n\rEmailResponse\x12\x11\n\tmessageId\x18\x01 \x01(\t2I\n\x0c\x45mailService\x12\x39\n\x08SendMail\x12\x14.protos.EmailRequest\x1a\x15.protos.EmailResponse\"\x00\x42!\n\x11\x63om.apkpure.protoB\x0c\x45mailServiceb\x06proto3')
)




_EMAILREQUEST = _descriptor.Descriptor(
  name='EmailRequest',
  full_name='protos.EmailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='protos.EmailRequest.from', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='protos.EmailRequest.to', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cc', full_name='protos.EmailRequest.cc', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subject', full_name='protos.EmailRequest.subject', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='charset', full_name='protos.EmailRequest.charset', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='textBody', full_name='protos.EmailRequest.textBody', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='htmlBody', full_name='protos.EmailRequest.htmlBody', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=149,
)


_EMAILRESPONSE = _descriptor.Descriptor(
  name='EmailResponse',
  full_name='protos.EmailResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageId', full_name='protos.EmailResponse.messageId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['EmailRequest'] = _EMAILREQUEST
DESCRIPTOR.message_types_by_name['EmailResponse'] = _EMAILRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailRequest = _reflection.GeneratedProtocolMessageType('EmailRequest', (_message.Message,), dict(
  DESCRIPTOR = _EMAILREQUEST,
  __module__ = 'aws_email_pb2'
  # @@protoc_insertion_point(class_scope:protos.EmailRequest)
  ))
_sym_db.RegisterMessage(EmailRequest)

EmailResponse = _reflection.GeneratedProtocolMessageType('EmailResponse', (_message.Message,), dict(
  DESCRIPTOR = _EMAILRESPONSE,
  __module__ = 'aws_email_pb2'
  # @@protoc_insertion_point(class_scope:protos.EmailResponse)
  ))
_sym_db.RegisterMessage(EmailResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021com.apkpure.protoB\014EmailService'))

_EMAILSERVICE = _descriptor.ServiceDescriptor(
  name='EmailService',
  full_name='protos.EmailService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=187,
  serialized_end=260,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMail',
    full_name='protos.EmailService.SendMail',
    index=0,
    containing_service=None,
    input_type=_EMAILREQUEST,
    output_type=_EMAILRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAILSERVICE)

DESCRIPTOR.services_by_name['EmailService'] = _EMAILSERVICE

# @@protoc_insertion_point(module_scope)
